# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop
- feature*

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - script: |
        java -version
        javac -version
      displayName: 'Check Java Version'

    - task: Maven@4
      displayName: Build Project
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        
          # Step to copy files to ArtifactStagingDirectory
    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/dc-glx-services
        cp -R dist/* $(Build.ArtifactStagingDirectory)/dc-glx-galaxy/
      displayName: 'Copy files to Artifact Staging Directory'

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'docker image'
        repository: 'prasannasurya12/cafyf-code-galaxy-service'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
           43
