# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop
- feature*

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - script: |
        java -version
        javac -version
      displayName: 'Check Java Version'

    - task: Maven@4
      displayName: Build Project
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        
          # Step to copy files to ArtifactStagingDirectory
    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/dc-glx-services/target  # Create target directory in staging
        cp target/*.jar $(Build.ArtifactStagingDirectory)/dc-glx-services/target/app.jar  # Copy JAR dynamically
        cp Dockerfile $(Build.ArtifactStagingDirectory)/dc-glx-services/Dockerfile  # Ensure the Dockerfile is copied
        displayName: 'Copy JAR and Dockerfile to Artifact Staging Directory'