# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop
- feature*

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - script: |
        java -version
        javac -version
      displayName: 'Check Java Version'

    - task: Maven@4
      displayName: Build Project
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        containerRegistry: 'docker image'
        repository: 'prasannasurya12/cafyf-code-galaxy-service'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    - script: |
          # Capture the image ID after the Docker build
           MAGE_ID=$(docker images -q prasannasurya12/cafyf-code-galaxy-service:latest)
          if [ -z "$IMAGE_ID" ]; then
          echo "No image ID found."
          else
          echo "Docker build completed with image ID: $IMAGE_ID" > $(Pipeline.Workspace)/docker_output.txt
          fi
      displayName: 'Capture Docker Output'


    - script: |
          # Save the Docker image to a tar file
          mkdir -p $(Build.ArtifactStagingDirectory)/dc-glx-services
          docker save prasannasurya12/cafyf-code-galaxy-service:latest -o $(Build.ArtifactStagingDirectory)/dc-glx-services/cafyf-code-galaxy-service.tar
      displayName: 'Save Docker Image to Artifact Staging Directory'

      # Step to publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/dc-glx-services'
        ArtifactName: 'dc-glx-services'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts' 